name: JunkiePass
authors: [Orgys, Risks]
version: 1.0-SNAPSHOT
depend: [JCore, Athena, PrisonMines, JShards, TokenEnchant, Votifier, EZRanksPro, EZPrestige]
softdepend: [DeliveryManX]
main: com.minejunkie.junkiepass.JunkiePass