name: JunkiePass
authors: [Orgys, Risks]
version: 1.0-SNAPSHOT
depend: [JCore, Athena, PrisonMines, TokenEnchant, EZRanksPro, EZPrestige]
softdepend: [DeliveryManX, Votifier]
main: com.minejunkie.junkiepass.JunkiePass